"use client";

import React, { useState } from "react";
// 👇 Added 'Monitor' to the imports
import { ShieldCheck, Smartphone, QrCode, CheckCircle2, Lock, Monitor } from "lucide-react";

export default function SecurityTab() {
  const [twoFactorEnabled, setTwoFactorEnabled] = useState(false);
  const [showSetup, setShowSetup] = useState(false);

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
      
      {/* Header */}
      <div>
        <h2 className="text-lg font-bold text-slate-900 dark:text-white">Security & Authentication</h2>
        <p className="text-sm text-slate-500">Manage two-factor authentication and active sessions.</p>
      </div>

      {/* 2FA Card */}
      <div className={`p-6 rounded-2xl border transition-all ${twoFactorEnabled ? 'bg-emerald-50/50 border-emerald-200 dark:border-emerald-900/30' : 'bg-white border-slate-200 dark:border-slate-800'}`}>
        <div className="flex justify-between items-start">
            <div className="flex gap-4">
                <div className={`p-3 rounded-xl ${twoFactorEnabled ? 'bg-emerald-100 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}>
                    <Smartphone className="w-6 h-6" />
                </div>
                <div>
                    <h3 className="font-bold text-slate-900 dark:text-white">Two-Factor Authentication (2FA)</h3>
                    <p className="text-sm text-slate-500 mt-1 max-w-sm">
                        Secure your account by requiring an authentication code from your mobile app when logging in.
                    </p>
                </div>
            </div>
            
            {!showSetup && !twoFactorEnabled && (
                <button 
                    onClick={() => setShowSetup(true)}
                    className="px-4 py-2 bg-slate-900 dark:bg-white text-white dark:text-slate-900 text-sm font-bold rounded-lg"
                >
                    Enable 2FA
                </button>
            )}

            {twoFactorEnabled && (
                <button 
                    onClick={() => setTwoFactorEnabled(false)}
                    className="px-4 py-2 border border-rose-200 text-rose-600 hover:bg-rose-50 text-sm font-bold rounded-lg"
                >
                    Disable
                </button>
            )}
        </div>

        {/* Setup Flow (Mock) */}
        {showSetup && !twoFactorEnabled && (
            <div className="mt-6 pt-6 border-t border-slate-200 dark:border-slate-800 animate-in slide-in-from-top-2">
                <div className="flex gap-8">
                    <div className="w-32 h-32 bg-white p-2 rounded-lg border border-slate-200 shadow-sm flex items-center justify-center">
                        <QrCode className="w-24 h-24 text-slate-900" />
                    </div>
                    <div className="flex-1 space-y-4">
                        <ol className="list-decimal list-inside text-sm text-slate-600 space-y-2">
                            <li>Open Google Authenticator or Authy on your phone.</li>
                            <li>Scan the QR code displayed on the left.</li>
                            <li>Enter the 6-digit code generated by the app below.</li>
                        </ol>
                        <div className="flex gap-3">
                            <input type="text" placeholder="000 000" className="w-32 text-center text-lg tracking-widest font-mono p-2 rounded border border-slate-300 focus:ring-2 focus:ring-indigo-500 outline-none" />
                            <button 
                                onClick={() => { setTwoFactorEnabled(true); setShowSetup(false); }}
                                className="px-4 py-2 bg-indigo-600 text-white font-bold rounded-lg text-sm"
                            >
                                Verify & Activate
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        )}
      </div>

      <hr className="border-slate-100 dark:border-slate-800" />

      {/* Device History */}
      <div>
          <h3 className="font-bold text-slate-900 dark:text-white mb-4">Device History</h3>
          <div className="space-y-3">
              <DeviceRow 
                icon={<Monitor className="w-4 h-4"/>} 
                name="Chrome on macOS" 
                location="Pretoria, ZA" 
                active 
              />
              <DeviceRow 
                icon={<Smartphone className="w-4 h-4"/>} 
                name="Safari on iPhone 14" 
                location="Johannesburg, ZA" 
                lastActive="2 days ago" 
              />
          </div>
      </div>

    </div>
  );
}

function DeviceRow({ icon, name, location, active, lastActive }: any) {
    return (
        <div className="flex items-center justify-between p-4 bg-slate-50 dark:bg-slate-900/50 rounded-xl border border-slate-200 dark:border-slate-800">
            <div className="flex items-center gap-3">
                <div className="text-slate-400">{icon}</div>
                <div>
                    <div className="text-sm font-bold text-slate-700 dark:text-slate-200">{name}</div>
                    <div className="text-xs text-slate-500">{location}</div>
                </div>
            </div>
            <div className="text-xs">
                {active ? (
                    <span className="flex items-center gap-1.5 text-emerald-600 font-medium px-2 py-1 bg-emerald-50 rounded-full">
                        <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" /> Active now
                    </span>
                ) : (
                    <span className="text-slate-400">{lastActive}</span>
                )}
            </div>
        </div>
    )
}